### ISSUE TITLE
permission_denied: Client doesn't have permission to access the desired data.

### ISSUE THREAD

**Issue by thomas-tewelde** [sararob/ionic-fb-groceries#3]
>  at Error (native)
>     at J (https://cdn.firebase.com/js/client/2.2.4/firebase.js:120:36)
>     at Object.J (https://cdn.firebase.com/js/client/2.2.4/firebase.js:201:378)
>     at https://cdn.firebase.com/js/client/2.2.4/firebase.js:187:3
>     at wh.h.Fd (https://cdn.firebase.com/js/client/2.2.4/firebase.js:191:104)
>     at kh.Fd (https://cdn.firebase.com/js/client/2.2.4/firebase.js:182:364)
>     at ch.wg (https://cdn.firebase.com/js/client/2.2.4/firebase.js:180:281)
>     at fh (https://cdn.firebase.com/js/client/2.2.4/firebase.js:174:464)
>     at WebSocket.va.onmessage (https://cdn.firebase.com/js/client/2.2.4/firebase.js:173:245)(anonymous function) @ ionic.bundle.js:20306c.$$error @ angularfire.min.js:12(anonymous function) @ angularfire.min.js:12(anonymous function) @ angularfire.min.js:12forEach @ ionic.bundle.js:9022g @ angularfire.min.js:12(anonymous function) @ ionic.bundle.js:24922completeOutstandingRequest @ ionic.bundle.js:13604(anonymous function) @ ionic.bundle.js:13984
> ionic.bundle.js:20306 destroy called for FirebaseArray: https://*************.firebaseio.com/items
> ionic.bundle.js:20306 TypeError: Cannot read property '$$error' of null
>     at angularfire.min.js:12
>     at angularfire.min.js:12
>     at Object.forEach (ionic.bundle.js:9022)
>     at g (angularfire.min.js:12)
>     at ionic.bundle.js:24922
>     at completeOutstandingRequest (ionic.bundle.js:13604)
>     at ionic.bundle.js:13984

**Comment by thomas-tewelde** [comment]
i my firebase dashboard, i went to go to database then rules and change permissions eg:

```
{
  "rules": {
    ".read": "true",
    ".write": "true"
  }
}
```
